
# 💖 These are supported funding model platforms for InfraForge

# Primary funding platforms
github: [gauravchile]
buy_me_a_coffee: gauravchile

# Custom link(s)
custom: ['https://buymeacoffee.com/gauravchile']

# Notes:
# - The "Sponsor" button on GitHub will automatically display both GitHub Sponsors and Buy Me a Coffee.
# - Add more platforms (like Patreon or Open Collective) here later if activated.
# - Keep this file versioned under .github/FUNDING.yml for visibility across all repositories.
